// @ts-nocheck
'use client'

// Attach historical reference notes to any Cortex item (a phase, a task, an
// agent, an automation, a lead). Shows a compact trigger that badges the note
// count; opens a log where you can read past notes, add one, or have the AI
// auto-suggest a context-aware note you can accept, edit, or discard. The
// suggestion is generated by the ONE existing coach (/api/coach) — no second
// model, no second runtime.

import { useState } from 'react'
import { useEntityNotes } from '@/lib/hooks/useEntityNotes'
import { DocumentIcon, CloseIcon, PlusIcon, TrashIcon, LightningIcon, CheckIcon } from '@/components/icons'
import { cn } from '@/lib/utils'

export function NoteButton({ entityType, entityId, label, context = '', compact = false, className }: {
  entityType: string; entityId: string; label: string; context?: string; compact?: boolean; className?: string
}) {
  const [open, setOpen] = useState(false)
  const { notes, count, loading, add, remove } = useEntityNotes(entityType, open ? entityId : null)
  const [draft, setDraft] = useState('')
  const [aiDraft, setAiDraft] = useState(false)
  const [suggesting, setSuggesting] = useState(false)

  const suggest = async () => {
    if (suggesting) return
    setSuggesting(true); setDraft(''); setAiDraft(true)
    try {
      const res = await fetch('/api/coach', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: `Draft ONE short reference note (1–2 sentences, first person, no preamble, no markdown) I can save against this item in my Cortex: "${label}". Context: ${context || 'general'}. Write it as a practical log/insight I'd want to remember next time I look at this — concrete and specific.`,
          pageContext: 'Cortex notes',
        }),
      })
      if (res.ok && res.body) {
        const reader = res.body.getReader(); const dec = new TextDecoder(); let acc = ''
        while (true) { const { done, value } = await reader.read(); if (done) break; acc += dec.decode(value, { stream: true }); setDraft(acc.trim()) }
      }
    } catch { /* leave whatever streamed in */ }
    finally { setSuggesting(false) }
  }

  const save = () => { const t = draft.trim(); if (!t) return; add(t, aiDraft); setDraft(''); setAiDraft(false) }

  return (
    <>
      <button onClick={e => { e.stopPropagation(); setOpen(true) }} aria-label={`Notes for ${label}`} title="Reference notes"
        className={cn('relative flex shrink-0 items-center gap-1 rounded-md border border-border bg-bdrbg px-2 py-1 text-[10.5px] font-[700] text-gray hover:text-navy', className)}>
        <DocumentIcon size={compact ? 11 : 12} />
        {!compact && <span>Notes</span>}
        {count > 0 && <span className="flex h-4 min-w-4 items-center justify-center rounded-full bg-teal px-1 text-[9px] font-[800] text-white">{count}</span>}
      </button>

      {open && (
        <div className="fixed inset-0 z-[1055] flex items-center justify-center bg-dark-text/50 p-4" onClick={() => setOpen(false)}>
          <div className="flex max-h-[85vh] w-full max-w-md flex-col rounded-2xl bg-card shadow-modal" onClick={e => e.stopPropagation()}>
            <div className="flex items-start justify-between gap-3 border-b border-border p-4">
              <div className="min-w-0">
                <div className="text-[10px] font-[800] uppercase tracking-wide text-gray">Reference notes</div>
                <h2 className="truncate text-[15px] font-[800] text-dark-text">{label}</h2>
              </div>
              <button onClick={() => setOpen(false)} aria-label="Close" className="shrink-0 text-gray hover:text-dark-text"><CloseIcon size={18} /></button>
            </div>

            {/* Composer */}
            <div className="border-b border-border p-3">
              <textarea value={draft} onChange={e => { setDraft(e.target.value); if (aiDraft) setAiDraft(false) }} rows={2}
                placeholder="Log a note, insight, or decision…" className="w-full resize-none rounded-xl border border-border bg-bdrbg px-3 py-2 text-[13px] outline-none placeholder-gray focus:border-navy/40" />
              <div className="mt-2 flex items-center gap-2">
                <button onClick={suggest} disabled={suggesting} className="flex items-center gap-1.5 rounded-lg bg-teal/10 px-2.5 py-1.5 text-[11.5px] font-[700] text-teal disabled:opacity-60">
                  <LightningIcon size={12} />{suggesting ? 'Thinking…' : 'AI suggest a note'}
                </button>
                {aiDraft && !suggesting && draft && <span className="text-[10.5px] font-[600] text-gray">AI draft — edit or save</span>}
                <div className="flex-1" />
                <button onClick={save} disabled={!draft.trim()} className={cn('flex items-center gap-1 rounded-lg px-3 py-1.5 text-[12px] font-[800] text-white', draft.trim() ? 'bg-navy' : 'bg-gray/40')}><PlusIcon size={12} /> Save</button>
              </div>
            </div>

            {/* Log */}
            <div className="flex-1 space-y-2 overflow-y-auto p-3">
              {loading ? (
                <div className="py-6 text-center text-[12px] text-gray">Loading…</div>
              ) : notes.length === 0 ? (
                <div className="py-6 text-center text-[12px] text-gray">No notes yet. Log the first one, or let the AI suggest one.</div>
              ) : notes.map(n => (
                <div key={n.id} className="rounded-xl border border-border bg-bdrbg p-3">
                  <div className="flex items-start gap-2">
                    {n.ai_suggested && <span className="mt-0.5 flex h-4 shrink-0 items-center gap-0.5 rounded bg-teal/10 px-1 text-[9px] font-[800] text-teal"><LightningIcon size={9} />AI</span>}
                    <p className="min-w-0 flex-1 whitespace-pre-wrap text-[13px] leading-relaxed text-dark-text">{n.body}</p>
                    <button onClick={() => remove(n.id)} aria-label="Delete note" className="shrink-0 text-gray hover:text-error"><TrashIcon size={13} /></button>
                  </div>
                  <div className="mt-1.5 text-[10px] text-gray">{new Date(n.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </>
  )
}
