import type { CompetitorsMap } from './types';

export const COMPETITORS: CompetitorsMap = 
{
  ck: {
    name:"Credit Karma", threat:"high", pill:"HIGH THREAT",
    sub:"Free, ad-supported · VantageScore 3.0 · TransUnion + Equifax only · No partner program",
    link:"https://www.creditkarma.com", linkLabel:"creditkarma.com",
    blocks:[
      { type:"OVERVIEW", sub:"profile", pill:"#14B8A6", tag:"Monitor", tagBg:"#CCFBF1", tagColor:"#0D9488",
        title:"Credit Karma — Core Profile",
        summary:"Free, Intuit-owned, 100M+ members. You're the product, not the customer — and Experian is never included, on any tier.",
        body:"Intuit subsidiary since December 2020, 100M+ members, completely free to the user. VantageScore 3.0 pulled from TransUnion and Equifax only — <span class='hl'>no Experian, ever, on any tier.</span> The product exists to put a number in front of you so Credit Karma can sell that attention to lenders and card issuers. You are not the customer. You are the inventory." },
      { type:"THE REAL REASON", sub:"why this gap exists", pill:"#94A3B8", tag:"Business Model", tagBg:"#F1F5F9", tagColor:"#475569",
        title:"Why Credit Karma will never close the Experian gap or build a score-improvement engine",
        summary:"A tool that actually fixes scores shrinks the pool of credit-shopping users Credit Karma sells to lenders — so it never will.",
        body:"This isn't an oversight — it's the business model working exactly as designed. Credit Karma's revenue comes from matching users to credit card and loan offers; <span class='hl'>a tool that actually fixes your score reduces the pool of 'still shopping for credit' users Credit Karma can monetize.</span> Building a real, patented score-improvement engine like ScoreBuilder® or paying for a third bureau adds cost with no upside to that ad model. SmartCredit's revenue comes from the subscription itself, so the incentive runs the opposite direction: the more your client's score improves, the more they trust the platform and stay enrolled." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"They're structurally blind to Experian — forever",
        summary:"Credit Karma will never show Experian data. SmartCredit covers all three bureaus.",
        body:"Credit Karma monitors TransUnion and Equifax only. <span class='hl'>If your client's worst derogatory items live on Experian, Credit Karma will never show them — not because of a bug, but because Intuit has never built that integration.</span> SmartCredit's Premium plan includes one full 3-bureau report monthly, and 3-bureau access is available as an add-on on Basic — either way, your client gets visibility Credit Karma structurally cannot provide." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"You earn real, documented commission. CK pays agencies nothing.",
        summary:"Credit Karma pays agencies $0. SmartCredit pays $5–$15 in monthly commission per active client.",
        body:"Credit Karma has no affiliate program, no co-brand option, and no revenue share of any kind for agencies. <span class='hl'>SmartCredit's Co-Brand PLUS+ program pays $5–$15 in monthly commission per active client</span>, scales with enrollment volume, and builds you a hosted, branded site. Credit Karma makes money off your clients. SmartCredit pays you to bring them in." },
      { type:"FAIR TRADE-OFF", sub:"be honest about this", pill:"#F59E0B", tag:"Genuine Gap", tagBg:"#FEF3C7", tagColor:"#92400E",
        title:"Where Credit Karma genuinely wins — don't pretend otherwise",
        summary:"Free beats paid on price, full stop. Don't fight that — reposition: Credit Karma checks a number, SmartCredit fixes one.",
        body:"Free is free. A client with no budget and no urgency will choose $0 over $19.95 every time, and no script changes that math. Credit Karma's mobile app is also polished and familiar — most clients have already used it before they ever talk to your agency. <span class='hl'>Don't try to out-argue 'free.' Out-position it instead:</span> Credit Karma is a fine place to check a number. It is not a place to fix one. That's the honest distinction, and it's the one that actually holds up under scrutiny." },
      { type:"TALK TRACK", sub:"scenario 1", pill:"#6366F1", tag:"Overcome", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"'My clients already use Credit Karma — it's free'",
        summary:"Free is great for awareness; it can't fix a score by design. Credit Karma's Experian blind spot is permanent, not a gap you wait out.",
        body:"\"Free is exactly why Credit Karma works for awareness — and exactly why it stops there. It can't, by design: a tool that fixes your score is bad for an ad-revenue business. ScoreBuilder® gives your clients a 120-day roadmap, ScoreBoost™ lets them simulate outcomes before they apply, and Credit Karma is structurally blind to Experian — not temporarily, permanently. Every negative item sitting on that bureau is invisible to a Credit Karma user. <span class='hl'>That's not a feature gap you wait out — it's a blind spot you close today.</span>\"" },
      { type:"TALK TRACK", sub:"scenario 2", pill:"#6366F1", tag:"Reframe", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"'CK shows my clients loan offers too'",
        summary:"Credit Karma's offers are paid placements, not real matches — they generate hard inquiries with no qualification check.",
        body:"\"Those are paid placements — Credit Karma gets paid whether or not your client actually qualifies. They click, they apply, they take a hard inquiry, and a meaningful share get declined. SmartCredit's myLONA® marketplace only surfaces offers matched to the client's real, current score. <span class='hl'>Fewer wasted inquiries, fewer declines that hurt the score you're working to build.</span> That protects the client and protects your agency's name.\"" },
      { type:"TALK TRACK", sub:"scenario 3", pill:"#6366F1", tag:"Close", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"'Won't clients resist paying when CK is free?'",
        summary:"Reframe the question: it was never 'free vs. paid.' It's 'monitoring vs. actually moving the number.'",
        body:"\"Here's the honest answer: SmartCredit isn't always cheaper than every free tool — it can't be, free is free. But your clients aren't hiring you to find a free app. They're hiring you to fix a number that's costing them thousands in interest. At $19.95–$29.95 a month, SmartCredit is a rounding error next to one improved interest rate on an auto loan or mortgage. <span class='hl'>The question was never 'free vs. paid.' It's 'monitoring vs. moving the number.'</span> Only one of those tools actually does the job you were hired for.\"" },
      { type:"LANDMINE", sub:"question 1", pill:"#F59E0B", tag:"Plant", tagBg:"#FEF9C3", tagColor:"#92400E",
        title:"Which bureau has the most negative items for your typical client?",
        summary:"If it's Experian, Credit Karma shows your client nothing — zero visibility, not partial.",
        body:"\"If the honest answer is Experian, your client on Credit Karma has <span class='hl'>zero visibility into their single biggest problem</span> — not a partial view, zero. Credit Karma has never integrated Experian, and there's no roadmap suggesting that changes.\"" },
      { type:"2026 INTEL", sub:"live data", pill:"#7C3AED", tag:"New", tagBg:"#EDE9FE", tagColor:"#6D28D9",
        title:"Credit Karma Plus is rolling out — even Intuit is admitting 'free' has a ceiling",
        summary:"Intuit is launching a paid tier (June 2026) — quiet proof that free monitoring alone was never the finish line.",
        body:"Intuit is launching a paid tier called <span class='hl'>Credit Karma Plus</span> (June 2026), adding identity protection, web data removal, bill negotiation, and paid tax help. Read between the lines: the company built entirely on 'free' is now charging for the features that actually protect and improve a financial life. <em>That's not a coincidence — that's market validation that monitoring alone was never the finish line.</em>" }
    ]
  },
  mf: {
    name:"myFICO", threat:"med", pill:"MEDIUM THREAT",
    sub:"Fair Isaac Corp · $19.95–$39.95/mo · No annual plan, no free trial · The only competitor selling the actual FICO® score",
    link:"https://www.myfico.com", linkLabel:"myfico.com",
    blocks:[
      { type:"OVERVIEW", sub:"profile", pill:"#14B8A6", tag:"Monitor", tagBg:"#CCFBF1", tagColor:"#0D9488",
        title:"myFICO — Core Profile",
        summary:"Fair Isaac's own consumer arm — no annual discount, no free trial, full retail every month.",
        body:"The direct consumer arm of Fair Isaac Corporation — the company that owns and licenses the FICO® score itself. Plans: Basic ($8.49–$19.95, 1-bureau), Advanced (~$19.99–$29.95, 3-bureau quarterly), Premier ($29.95–$39.95, 3-bureau monthly). <span class='hl'>No annual billing discount on any tier, no free trial.</span> You pay full retail every month, indefinitely." },
      { type:"THE REAL REASON", sub:"why this gap exists", pill:"#94A3B8", tag:"Industry Economics", tagBg:"#F1F5F9", tagColor:"#475569",
        title:"Why myFICO is expensive and SmartCredit isn't — and why that's not a knock on either",
        summary:"FICO carries a real per-pull licensing cost; VantageScore was built to be cheaper to distribute at scale — that's the entire price gap.",
        body:"This is the single most useful piece of industry knowledge in your toolkit. <span class='hl'>FICO scores are licensed directly from Fair Isaac, and that licensing has historically carried a real per-pull cost that gets passed to the consumer.</span> VantageScore — built jointly by all three bureaus specifically to be easier and cheaper to distribute at scale — is what nearly every white-label and agency-channel platform uses, SmartCredit included. This is exactly why myFICO is the priciest service in this entire battlecard set: you're paying a licensing premium for the brand name on the score, not a fundamentally better measurement of risk." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"$39.95/mo, no annual discount, no trial — and reviewers have noticed",
        summary:"Reviewers call it pricier than LifeLock with fewer features. SmartCredit costs $10/month less and actually ships an improvement plan.",
        body:"U.S. News declined to rank myFICO among the best identity protection services of 2026, citing price relative to features. <span class='hl'>Tom's Guide went further: myFICO 'tops the cost of Norton LifeLock'</span> while lacking a credit freeze button, family plan, or data breach alerts. SmartCredit's top tier costs $10/month less and ships an active 120-day improvement plan myFICO has never built." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"A simulator tells you what might happen. ScoreBuilder® tells you what to do.",
        summary:"myFICO's simulator reacts after the fact. ScoreBuilder® hands clients a 120-day plan before they act.",
        body:"myFICO's simulator answers 'what if I paid this down' after the fact. <span class='hl'>SmartCredit's ScoreBuilder® hands your client a personalized 120-day action plan up front</span>, and ScoreBoost™ lets them preview the outcome of a move before they make it. One is a calculator. The other is a coach." },
      { type:"FAIR TRADE-OFF", sub:"be honest about this", pill:"#F59E0B", tag:"Genuine Gap", tagBg:"#FEF3C7", tagColor:"#92400E",
        title:"myFICO genuinely sells the score lenders actually pull — don't dodge that",
        summary:"True: roughly 90% of lenders pull FICO, not VantageScore. Say this before a sharp prospect makes you.",
        body:"This is real and worth saying plainly: <span class='hl'>roughly 90% of top lenders make credit decisions using a FICO score, not VantageScore.</span> For a client three weeks from a mortgage closing who wants to know exactly what the underwriter will see, myFICO's number is the more literal answer. SmartCredit doesn't sell the FICO score — it sells the tools that move the behaviors FICO and VantageScore both score. Say this part out loud before a sharp prospect makes you say it for them." },
      { type:"TALK TRACK", sub:"scenario 1", pill:"#6366F1", tag:"Bridge", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"'My clients need the FICO score, not VantageScore'",
        summary:"FICO and VantageScore move on the same behaviors — fixing one moves both. myFICO shows the number; it can't tell clients what to do about it.",
        body:"\"You're right that most lenders pull FICO — and it's worth being upfront about that. Here's the part that matters more in practice: FICO and VantageScore are scored on the exact same behaviors — on-time payments, utilization, derogatory items. When ScoreBuilder® has your client pay down a card or dispute an error, <span class='hl'>that action moves both scores, not just one.</span> myFICO can show your client the FICO number; it can't tell them what to do about it. At $39.95/month with no annual discount, you're paying a premium to watch a number you still don't know how to move.\"" },
      { type:"TALK TRACK", sub:"scenario 2", pill:"#6366F1", tag:"Qualify", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Client is genuinely close to a mortgage and wants FICO specifically",
        summary:"For score-ready clients near closing, a one-time FICO pull is reasonable. Everyone else needs ScoreBuilder® first.",
        body:"\"For a client who's already score-ready and weeks from underwriting, pulling an actual FICO is a reasonable, one-time check — and there's no shame in saying so. But that's a small fraction of the people in active credit repair. <span class='hl'>Most clients aren't mortgage-ready yet — they need ScoreBuilder® to get there first,</span> then a one-time FICO pull near closing if they want it. SmartCredit gets them to the goal line; myFICO just shows them how far they have left to walk, every month, at full price.\"" },
      { type:"TALK TRACK", sub:"scenario 3", pill:"#6366F1", tag:"Cost", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Straight pricing comparison",
        summary:"$479/year for a number with no action plan and no partner program. SmartCredit costs less and includes both.",
        body:"\"$39.95 a month, no annual discount, no trial — that's over $479 a year for a number with no action plan, no Action Buttons™, no lending marketplace, and no agency partner program. SmartCredit's top tier runs $27.95–$29.95 and includes all of that plus real commission back to your agency. <span class='hl'>You're not comparing two credit tools — you're comparing a meter to a mechanic.</span>\"" },
      { type:"LANDMINE", sub:"question 1", pill:"#F59E0B", tag:"Plant", tagBg:"#FEF9C3", tagColor:"#92400E",
        title:"When a myFICO client finds an error, what's the actual next step?",
        summary:"myFICO shows the problem; it can't contact the creditor. Action Buttons™ reach 30,000+ creditors directly.",
        body:"\"myFICO can show you the problem clearly. It has no mechanism to contact the creditor for you. <span class='hl'>SmartCredit's Action Buttons™ connect directly to 30,000+ creditors</span> — the only patented direct-creditor communication tool anywhere in this comparison.\"" },
      { type:"2026 INTEL", sub:"live data", pill:"#7C3AED", tag:"New", tagBg:"#EDE9FE", tagColor:"#6D28D9",
        title:"U.S. News left myFICO off its 2026 best-of list entirely",
        summary:"Left off U.S. News' 2026 best-of list for high price and thin features — the FICO premium is getting harder to justify.",
        body:"U.S. News' 2026 review didn't rank myFICO among the best identity protection services, citing <span class='hl'>high prices relative to a thin feature set.</span> Tom's Guide separately noted it costs more than Norton LifeLock while delivering fewer protections. The 'official FICO' premium is increasingly hard for myFICO to justify on value alone." }
    ]
  },
  ex: {
    name:"Experian IW", threat:"med", pill:"MEDIUM THREAT",
    sub:"Major bureau · Free–$34.99/mo · IdentityWorks discontinuing new signups, folding into CreditWorks Premium",
    link:"https://www.experian.com/protection/identitytheft-protection-best-id-theft-monitoring", linkLabel:"experian.com",
    blocks:[
      { type:"OVERVIEW", sub:"profile", pill:"#14B8A6", tag:"Bureau", tagBg:"#CCFBF1", tagColor:"#0D9488",
        title:"Experian IdentityWorks — Core Profile",
        summary:"A bureau monitoring its own data — and IdentityWorks is currently being discontinued, folding into CreditWorks Premium.",
        body:"One of the three major credit bureaus, monitoring its own data. IdentityWorks plans: Free (Experian-only), Premium (~$24.99/mo), Family (~$34.99/mo). <span class='hl'>Breaking: IdentityWorks is no longer accepting new direct subscriptions</span> — it's being folded into CreditWorks Premium. Independently confirmed to share user data with third parties for ad targeting." },
      { type:"THE REAL REASON", sub:"why this gap exists", pill:"#94A3B8", tag:"Structural Bias", tagBg:"#F1F5F9", tagColor:"#475569",
        title:"Why a credit bureau will never build a real score-improvement engine",
        summary:"A bureau's job is reporting what happened, not coaching what's next — a fundamentally different business than SmartCredit's.",
        body:"Experian's core business is selling data — to lenders, to advertisers, to anyone who needs to evaluate risk. <span class='hl'>A bureau's entire commercial incentive is to be an accurate, neutral reporter of what happened, not an active participant helping a consumer change the outcome.</span> That's not a criticism — it's structurally what a credit bureau is for. Building a ScoreBuilder®-style 120-day action plan would put Experian in the business of telling consumers how to behave differently, which sits oddly next to its other business of selling that exact behavioral data to advertisers. SmartCredit has no bureau business to protect, so it can build entirely toward the consumer's outcome." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"The product is in active sunset — and your prospect should know that before they commit",
        summary:"Mid-migration into CreditWorks Premium means an uncertain support team and roadmap right now.",
        body:"Experian is discontinuing new IdentityWorks signups and migrating everyone into CreditWorks Premium. <span class='hl'>A platform mid-transition means an uncertain support team, an uncertain roadmap, and an onboarding flow built for a product being phased out.</span> SmartCredit's platform and Co-Brand PLUS+ partner program are stable, actively maintained, and not in the middle of being merged into something else." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"Confirmed: Experian shares user data with advertisers",
        summary:"Independently confirmed: Experian shares user data with third-party advertisers — a real, fair trust point to raise.",
        body:"Independent 2026 reviews confirm Experian IdentityWorks shares user data with third parties for targeted advertising. <span class='hl'>If you're positioning your agency around protecting client trust and privacy, that's a real, fair point to raise</span> — not a cheap shot, a documented practice." },
      { type:"FAIR TRADE-OFF", sub:"be honest about this", pill:"#F59E0B", tag:"Genuine Gap", tagBg:"#FEF3C7", tagColor:"#92400E",
        title:"'Straight from the bureau' is a real credibility claim — acknowledge it",
        summary:"Bureau-direct data and real FICO scores are genuine credibility — but monitoring and improving are different jobs.",
        body:"Experian monitoring its own data has a kind of authority SmartCredit can't claim — it's the source, not a layer on top of the source. Premium plans also include actual FICO scores, which carries the same weight discussed with myFICO. <span class='hl'>Don't dismiss this as marketing.</span> The honest counter isn't 'their data is wrong' — it's that monitoring your own data and helping you improve it are two different jobs, and Experian was never built to do the second one." },
      { type:"TALK TRACK", sub:"scenario 1", pill:"#6366F1", tag:"Reframe", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"'They're a credit bureau — their data is the source'",
        summary:"Experian reports what happened; SmartCredit changes what happens next — different jobs entirely.",
        body:"\"That's fair — Experian's data on their own bureau is as accurate as it gets. But monitoring and improving are two different jobs, and Experian was built for the first one. <span class='hl'>A bureau's incentive is to report what happened, not to help your client change what happens next</span> — that's a different business entirely, and it's the business SmartCredit is actually in. ScoreBuilder® gives a personalized 120-day plan; Experian gives you a number and an alert.\"" },
      { type:"TALK TRACK", sub:"scenario 2", pill:"#6366F1", tag:"Upgrade", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Prospect or clients are on Experian's free tier",
        summary:"Free Experian covers one bureau only — two-thirds of a client's file stays invisible.",
        body:"\"The free Experian tier monitors Experian only — by definition, one of three bureaus. For a client with active disputes running across all three, that's blind to two-thirds of their file. SmartCredit's Premium plan includes a full 3-bureau report every month, and 3-bureau access is available as an add-on even on Basic. <span class='hl'>Either way, your client sees more of the picture than Experian's free plan will ever show them.</span>\"" },
      { type:"TALK TRACK", sub:"scenario 3", pill:"#6366F1", tag:"Intel", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Lead with the product transition risk",
        summary:"IdentityWorks is mid-migration into CreditWorks Premium right now — real uncertainty during a commitment decision.",
        body:"\"Worth knowing before you commit: Experian IdentityWorks isn't taking new direct subscriptions — it's being folded into CreditWorks Premium right now. That's real uncertainty around support, pricing, and the feature roadmap during the migration. SmartCredit's platform isn't mid-merger with anything; the partner program is stable and actively shipping.\"" },
      { type:"LANDMINE", sub:"question 1", pill:"#F59E0B", tag:"Plant", tagBg:"#FEF9C3", tagColor:"#92400E",
        title:"Are you building your client stack on a product that's currently being discontinued?",
        summary:"IdentityWorks is being phased out mid-migration — how comfortable is that for a client stack?",
        body:"\"IdentityWorks is folding into CreditWorks Premium mid-migration right now. <span class='hl'>How comfortable are you putting your clients on a platform in the middle of being phased out?</span>\"" },
      { type:"2026 INTEL", sub:"live data", pill:"#7C3AED", tag:"Breaking", tagBg:"#EDE9FE", tagColor:"#6D28D9",
        title:"IdentityWorks confirmed no longer accepting new direct subscriptions",
        summary:"Confirmed April 2026: IdentityWorks no longer takes new direct subscriptions, folding fully into CreditWorks Premium.",
        body:"Confirmed in an April 2026 Cybernews review: <span class='hl'>\"Experian IdentityWorks is no longer accepting new direct subscriptions. The service's technology has been integrated into CreditWorks Premium.\"</span> Any prospect comparing against 'Experian IdentityWorks' by name is comparing against a product actively being absorbed into something else." }
    ]
  },
  ll: {
    name:"LifeLock / Norton", threat:"med", pill:"MEDIUM THREAT",
    sub:"Gen Digital · $12.49–$34.99/mo intro pricing · Identity protection, zero score improvement",
    link:"https://lifelock.norton.com", linkLabel:"lifelock.norton.com",
    blocks:[
      { type:"OVERVIEW", sub:"profile", pill:"#14B8A6", tag:"Identity", tagBg:"#CCFBF1", tagColor:"#0D9488",
        title:"LifeLock / Norton 360 — Core Profile",
        summary:"Insurance-and-recovery focused, up to $3M coverage. Introductory pricing only — renewals run higher.",
        body:"Gen Digital, formerly NortonLifeLock. Plans: Core $12.49, Advanced $19.99, Total $34.99/mo — <span class='hl'>introductory pricing only; renewal pricing runs higher.</span> Bundled with Norton 360 antivirus on upper tiers. Up to $3M in identity theft insurance on the Ultimate Plus plan. VantageScore 3.0. No score-improvement tooling of any kind." },
      { type:"THE REAL REASON", sub:"why this gap exists", pill:"#94A3B8", tag:"Different Category", tagBg:"#F1F5F9", tagColor:"#475569",
        title:"Why LifeLock will never build a credit-improvement engine — it's solving a different problem",
        summary:"LifeLock solves insurance and recovery, not score-building — a fundamentally different engineering problem.",
        body:"LifeLock's entire product thesis is insurance and recovery: protect what exists, and pay out if it's stolen. <span class='hl'>That's a fundamentally different engineering and actuarial problem than 'help this specific person raise their score 40 points in 120 days.'</span> Building ScoreBuilder®-style tooling would mean LifeLock entering a product category — active credit coaching — that has nothing to do with the insurance underwriting and device-security business Gen Digital actually runs. This isn't a gap they're closing soon. It isn't the business they're in." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"Credit repair agencies sell score improvement. LifeLock sells insurance.",
        summary:"LifeLock protects what exists. SmartCredit builds what's still missing — different jobs entirely.",
        body:"LifeLock has <span class='hl'>zero score-improvement tools</span> — no action plan, no simulation, no creditor communication. It protects and insures what already exists. SmartCredit builds toward what the client still needs. Different jobs, and LifeLock's job was never the one your agency was hired to do." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"$7,969 in documented average savings beats a $3M ceiling almost nobody claims",
        summary:"$3M is a ceiling almost nobody hits. $7,969 is a documented average outcome — real money, not hypothetical.",
        body:"LifeLock's $3M insurance headline is genuinely strong marketing. Counter it with something more concrete: <span class='hl'>SmartCredit users average $7,969 in documented savings from better loan rates.</span> One is a maximum payout for a low-probability event. The other is real money, realized through a score that actually moved." },
      { type:"FAIR TRADE-OFF", sub:"be honest about this", pill:"#F59E0B", tag:"Genuine Gap", tagBg:"#FEF3C7", tagColor:"#92400E",
        title:"LifeLock's brand and insurance ceiling are real — say so",
        summary:"Real brand power and the highest insurance ceiling here — genuinely valuable for anxious post-theft clients.",
        body:"LifeLock is the most recognized name in identity protection for a reason, and a $3M coverage ceiling is the highest in this entire comparison. For a client who's already been through identity theft and is anxious about it happening again, <span class='hl'>that peace of mind has genuine value SmartCredit doesn't replicate.</span> The honest pitch isn't 'LifeLock is bad' — it's that insurance and improvement solve different problems, and most clients walking through your door need the second one more urgently than the first." },
      { type:"TALK TRACK", sub:"scenario 1", pill:"#6366F1", tag:"Reframe", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"'LifeLock has $3M in coverage'",
        summary:"Compare a rare $3M claim to a documented $7,969 average savings from a moved score — real money wins.",
        body:"\"That's real, and it's the strongest number in their pitch. But ask yourself which is more likely for your typical client: collecting on a $3M identity theft claim, or saving real money because their score moved enough to qualify for a better rate? <span class='hl'>SmartCredit users average $7,969 in documented loan savings</span> — that's not a ceiling nobody hits, it's an average outcome. LifeLock insures against a bad day. SmartCredit builds toward a better one.\"" },
      { type:"TALK TRACK", sub:"scenario 2", pill:"#6366F1", tag:"Category", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Prospect is bundling LifeLock with Norton antivirus",
        summary:"That bundle puts you in the antivirus business. SmartCredit stays entirely in your lane: credit improvement.",
        body:"\"That bundle makes sense for someone who wants device security and identity monitoring together — that's a legitimate combination. But it puts you in the antivirus business, which isn't your lane. <span class='hl'>SmartCredit is built end to end for credit improvement</span> — that focus is exactly what your clients are hiring your agency for, and it's not something a security bundle was ever designed to deliver.\"" },
      { type:"TALK TRACK", sub:"scenario 3", pill:"#6366F1", tag:"Cost", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Pricing — intro vs. renewal",
        summary:"Intro pricing looks competitive; renewal climbs without warning. SmartCredit's price never moves.",
        body:"\"LifeLock's intro pricing looks competitive at $12.49 a month — but that's a first-year rate. Renewal pricing climbs from there, and most clients don't realize the jump is coming until the bill changes. SmartCredit's pricing is the same in month two as it is in month one. <span class='hl'>And SmartCredit does something LifeLock fundamentally cannot</span> — give your client an actual plan to raise their score.\"" },
      { type:"LANDMINE", sub:"question 1", pill:"#F59E0B", tag:"Plant", tagBg:"#FEF9C3", tagColor:"#92400E",
        title:"What does LifeLock do to rebuild a score after identity theft?",
        summary:"LifeLock helps recover from theft — but offers no tool to rebuild the score that took the hit.",
        body:"\"LifeLock can alert your client and help them recover from theft — genuinely useful. But once the immediate damage is handled, <span class='hl'>what tool does LifeLock give them to actually rebuild the score</span> that took the hit?\"" },
      { type:"2026 INTEL", sub:"live data", pill:"#7C3AED", tag:"Pricing", tagBg:"#EDE9FE", tagColor:"#6D28D9",
        title:"LifeLock renewal pricing climbs meaningfully past the intro rate",
        summary:"Multiple 2026 reviews confirm renewal pricing jumps well past the intro rate, especially on upper tiers.",
        body:"Multiple 2026 reviews confirm <span class='hl'>LifeLock's introductory annual pricing is a steep discount against renewal.</span> Advanced and Total tiers in particular renew noticeably higher in year two. Clients who sign up on the intro number often don't see that increase coming until it hits their statement." }
    ]
  },
  idf: {
    name:"IdentityForce", threat:"med", pill:"MEDIUM THREAT",
    sub:"TransUnion subsidiary · $23.95–$37.90/mo · Comprehensive identity monitoring, zero credit improvement",
    link:"https://www.identityforce.com", linkLabel:"identityforce.com",
    blocks:[
      { type:"OVERVIEW", sub:"profile", pill:"#14B8A6", tag:"Monitor", tagBg:"#CCFBF1", tagColor:"#0D9488",
        title:"IdentityForce — Core Profile",
        summary:"TransUnion-owned, 40+ monitoring features. Pure protection — zero credit-improvement tools, no partner program.",
        body:"Now a TransUnion subsidiary. Plans: UltraSecure ($23.95/mo), UltraSecure+Credit ($37.90/mo). <span class='hl'>40+ identity monitoring features</span> — one of the deepest monitoring products on the market. Strictly protection-focused: zero credit-improvement tools, no lending marketplace, no agency partner program of any kind." },
      { type:"THE REAL REASON", sub:"why this gap exists", pill:"#94A3B8", tag:"Bureau-Owned", tagBg:"#F1F5F9", tagColor:"#475569",
        title:"Why a TransUnion subsidiary builds monitoring depth, not improvement tools",
        summary:"Bureau ownership produces monitoring infrastructure, not behavioral coaching — that's the whole gap.",
        body:"IdentityForce is owned by a credit bureau, and bureau-owned products tend to get built by people whose core expertise is data infrastructure and risk monitoring — not behavioral coaching or consumer UX. <span class='hl'>That's exactly the skillset that produces 40+ monitoring features and zero score-improvement tools.</span> It's not negligence; it's where the parent company's institutional strength actually lies. SmartCredit isn't bureau-owned, so its entire roadmap can be built around the one thing IdentityForce's structure doesn't naturally produce: helping a specific consumer raise a specific number." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"Zero credit-improvement tools at any price point",
        summary:"Even at $37.90/month, no action plan, no simulation, no creditor contact. SmartCredit ships all three for less.",
        body:"IdentityForce monitors identity threats deeply. But even at $37.90/month for UltraSecure+Credit, <span class='hl'>there is no 120-day plan, no simulation, no direct creditor communication.</span> SmartCredit delivers all three for $19.95–$29.95 — meaningfully less than IdentityForce's top tier." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"No partner program — IdentityForce pays agencies nothing",
        summary:"No commission, no portal, nothing for referring agencies. SmartCredit pays $5–$15/month per active client.",
        body:"IdentityForce has no co-brand program, no commission structure, no partner portal. Agencies that recommend it earn zero. <span class='hl'>SmartCredit's Co-Brand PLUS+ program pays $5–$15 in monthly commission per active enrollment</span>, builds you a co-branded site, and runs nurture sequences to protect retention." },
      { type:"FAIR TRADE-OFF", sub:"be honest about this", pill:"#F59E0B", tag:"Genuine Gap", tagBg:"#FEF3C7", tagColor:"#92400E",
        title:"IdentityForce is genuinely the deepest monitoring product here — say it plainly",
        summary:"40+ monitoring features is real depth — but most clients came to build a score, not just watch for threats.",
        body:"40+ monitoring features — SSN alerts, court records, payday loan tracking, sex offender registry checks — is real depth, and it's more comprehensive than what SmartCredit ships on the monitoring side specifically. <span class='hl'>For a client whose primary fear is identity theft rather than a low score, that depth has genuine value.</span> The honest distinction is the job: IdentityForce watches for threats. SmartCredit builds toward a number. Most of your clients walked in needing the second one." },
      { type:"TALK TRACK", sub:"scenario 1", pill:"#6366F1", tag:"Pivot", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Prospect values comprehensive identity monitoring",
        summary:"IdentityForce monitors; SmartCredit builds. At $37.90 versus $19.95–$29.95, you're paying more for less movement.",
        body:"\"IdentityForce is genuinely excellent at watching for threats — that part is real. But your clients didn't come to your agency to protect a bad score; they came to build a better one. IdentityForce monitors. SmartCredit builds. <span class='hl'>And at $37.90 a month versus SmartCredit's $19.95–$29.95,</span> you're paying more for a product that fundamentally cannot move the number your client is paying you to fix.\"" },
      { type:"TALK TRACK", sub:"scenario 2", pill:"#6366F1", tag:"Empathize", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Client has a history of identity theft",
        summary:"SmartCredit includes $1M fraud insurance and data removal standard — protection plus the tools to rebuild after.",
        body:"\"For a client who's already been through identity theft, monitoring genuinely matters — and SmartCredit includes $1M Whole-Family Fraud Insurance and PrivacyMaster® for online data removal standard. <span class='hl'>You get real protection plus the improvement tools to rebuild what the event damaged.</span> IdentityForce gives you the protection half of that equation and stops there.\"" },
      { type:"TALK TRACK", sub:"scenario 3", pill:"#6366F1", tag:"Revenue", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Agency revenue comparison",
        summary:"Zero partner economics at IdentityForce. SmartCredit pays $5–$15/month per active client, scaling with volume.",
        body:"\"IdentityForce has no partner program at all — you could refer a hundred clients and never see a dollar. SmartCredit's Co-Brand PLUS+ structure pays $5–$15 in monthly commission per active client, scaling with your enrollment volume, plus a co-branded site under your own logo. <span class='hl'>Nothing in this comparison matches that economics for your agency.</span>\"" },
      { type:"LANDMINE", sub:"question 1", pill:"#F59E0B", tag:"Plant", tagBg:"#FEF9C3", tagColor:"#92400E",
        title:"What does IdentityForce do to move a 520 score to 650?",
        summary:"IdentityForce watches for threats — it has no feature that actually moves a score from 520 to 680.",
        body:"\"IdentityForce watches for threats across 40+ data points. If a client's score is 520 and they need 680 to qualify for a mortgage — <span class='hl'>which specific feature in IdentityForce gets them there?</span> What's the actual plan?\"" },
      { type:"2026 INTEL", sub:"live data", pill:"#7C3AED", tag:"Structure", tagBg:"#EDE9FE", tagColor:"#6D28D9",
        title:"IdentityForce's corporate parent is a credit bureau — and the roadmap shows it",
        summary:"TransUnion ownership shapes the roadmap toward data infrastructure, away from consumer improvement tools.",
        body:"IdentityForce is owned by TransUnion, which means it's a <span class='hl'>bureau-owned monitoring product</span> first. That ownership shapes the roadmap toward data infrastructure and away from consumer-facing improvement tools — there's no indication that's changing." }
    ]
  },
  cs: {
    name:"Credit Sesame", threat:"low", pill:"LOW THREAT",
    sub:"Free TransUnion-only monitoring · Sesame Cash banking product causing documented score damage in 2026",
    link:"https://www.creditsesame.com", linkLabel:"creditsesame.com",
    blocks:[
      { type:"OVERVIEW", sub:"profile", pill:"#14B8A6", tag:"Free", tagBg:"#CCFBF1", tagColor:"#0D9488",
        title:"Credit Sesame — Core Profile",
        summary:"Free, TransUnion-only. Sesame Cash, its banking product, is causing documented 200+ point score drops in 2026.",
        body:"Free tier: daily TransUnion VantageScore, credit report, basic monitoring. Paid: Sesame+ (~$9.99/mo) and Sesame+ Complete (~$19.99/mo, 3-bureau). <span class='hl'>Critical 2026 issue: the Sesame Cash banking product is causing 200+ point score drops</span> from incorrect late-payment reporting, with affected users describing an inability to reach support." },
      { type:"THE REAL REASON", sub:"why this gap exists", pill:"#94A3B8", tag:"Growth Strategy", tagBg:"#F1F5F9", tagColor:"#475569",
        title:"Why a free credit app started running a bank account — and why it backfired",
        summary:"Sesame Cash was a growth bet into banking — now a credit app is running payment infrastructure outside its core competency.",
        body:"Credit Sesame's free credit monitoring doesn't generate much revenue on its own, so the company expanded into banking with Sesame Cash to build a second business line and increase how often users open the app. <span class='hl'>That's a reasonable growth strategy on paper, but it means a credit monitoring company is now also operating consumer banking infrastructure</span> — payment processing, account reporting, credit-bureau furnishing — outside its original core competency. The 2026 billing errors are a direct symptom of that expansion outrunning the operational maturity to support it." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Critical", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"Sesame Cash is actively damaging clients' scores right now",
        summary:"Verified 2026 reports: Sesame Cash caused 200+ point drops from bad late-payment reporting, with support unreachable.",
        body:"Multiple verified consumer complaints describe Sesame Cash causing <span class='hl'>200+ point score drops from incorrect late-payment reports</span> — one documented case at 271 points — with customers describing an inability to reach support. For a credit repair agency, pointing a client toward this product right now carries real, current liability." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"The free tier sees less than Credit Karma's free tier",
        summary:"Sesame's free plan covers TransUnion only — narrower visibility than every other free competitor here.",
        body:"Credit Karma's free plan monitors two bureaus (TransUnion and Equifax). <span class='hl'>Credit Sesame's free plan monitors only TransUnion</span> — the narrowest free-tier visibility of any competitor in this set. For a client running disputes across all three bureaus, that's the least complete picture available anywhere on this list." },
      { type:"FAIR TRADE-OFF", sub:"be honest about this", pill:"#F59E0B", tag:"Genuine Gap", tagBg:"#FEF3C7", tagColor:"#92400E",
        title:"Free with no card required is a real, low-friction entry point",
        summary:"Genuinely low-friction and useful for quick checks — the real risk is specifically Sesame Cash, not the core product.",
        body:"Credit Sesame's free plan requires no credit card and updates the score daily — genuinely useful for a client who just wants a quick check-in with zero commitment. <span class='hl'>Don't oversell the danger here either.</span> The honest, fact-based concern is specifically Sesame Cash, not the core free monitoring product, which is a reasonable (if limited) tool on its own." },
      { type:"TALK TRACK", sub:"scenario 1", pill:"#6366F1", tag:"Protect", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Sesame Cash is already in the conversation",
        summary:"Sesame Cash has caused real, documented 2026 score damage. ScoreBuilder® carries no banking-product risk.",
        body:"\"Credit Sesame's Sesame Cash product has caused real, documented damage in 2026 — verified reports of 200+ point score drops from billing errors that got reported straight to the bureaus, with affected users unable to get a human on the phone. For a client in active repair, that's the kind of setback that erases months of work overnight. <span class='hl'>SmartCredit's ScoreBuilder® is a patented plan with no banking product attached to it — nothing that can backfire the way Sesame Cash has.</span>\"" },
      { type:"TALK TRACK", sub:"scenario 2", pill:"#6366F1", tag:"Value", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Free plan vs. SmartCredit pricing",
        summary:"Single-bureau free coverage can't confirm whether dispute work is even showing up on the other two bureaus.",
        body:"\"Credit Sesame's free tier monitors TransUnion only — one of three bureaus. If you're disputing items across all three and your client can only see one, <span class='hl'>they can't even confirm whether your work is actually showing up</span> on the other two. SmartCredit's Premium tier gives a full 3-bureau report monthly, and 3-bureau access is available as an add-on even on Basic — either way, your client sees what's actually happening.\"" },
      { type:"TALK TRACK", sub:"scenario 3", pill:"#6366F1", tag:"Revenue", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Agency leaning on Credit Sesame as their free tool",
        summary:"No partner economics, and Sesame Cash carries real reputational risk if a client's score takes a hit mid-repair.",
        body:"\"Credit Sesame has no agency partner program — no commission, nothing. And right now the Sesame Cash situation means recommending it carries genuine reputational risk if a client's score takes a hit mid-repair; that comes back on your agency, not Credit Sesame. SmartCredit pays you $5–$15 in monthly commission per active client and is a product you can stand behind without a disclaimer.\"" },
      { type:"LANDMINE", sub:"question 1", pill:"#F59E0B", tag:"Plant", tagBg:"#FEF9C3", tagColor:"#92400E",
        title:"Are any of your current clients using Sesame Cash?",
        summary:"Multiple documented 200+ point drops tied to Sesame Cash in 2026 — worth checking before you proceed.",
        body:"\"There are multiple documented 2026 cases of 200+ point score drops tied to Sesame Cash billing errors. <span class='hl'>I'd want to make sure none of your active clients are on that product</span> while you're working to rebuild their credit.\"" },
      { type:"2026 INTEL", sub:"live data", pill:"#7C3AED", tag:"Critical", tagBg:"#EDE9FE", tagColor:"#6D28D9",
        title:"Sesame Cash billing errors causing verified, repeated score damage",
        summary:"Multiple platforms confirm a consistent 2026 pattern of incorrect late-payment reporting and unreachable support.",
        body:"WalletHub, ConsumerAffairs, and other platforms document a consistent 2026 pattern: <span class='hl'>Sesame Cash incorrectly reports late payments</span> on funded, active accounts. One documented case shows a 271-point drop. \"Do not use Sesame Cash\" warnings are widespread, and affected customers report being unable to reach support. This is an active reputational liability for Credit Sesame, not an isolated incident." }
    ]
  },
  mfsn: {
    name:"MyFreeScoreNow", threat:"med", pill:"MEDIUM THREAT",
    sub:"Seattle-based · $29.95/mo flat · Long-standing credit repair agency staple via Credit Repair Cloud",
    link:"https://www.myfreescorenow.com", linkLabel:"myfreescorenow.com",
    blocks:[
      { type:"OVERVIEW", sub:"profile", pill:"#14B8A6", tag:"Agency Staple", tagBg:"#CCFBF1", tagColor:"#0D9488",
        title:"MyFreeScoreNow (MFSN) — Core Profile",
        summary:"Decade-old credit-repair-channel staple. Flat $29.95/month, including a monthly 3-bureau report.",
        body:"Founded 2013 in Seattle, led by CEO Bruce Cornelius. <span class='hl'>$1 activation plus a 7-day trial, then a flat $29.95/month</span> that includes a monthly 3-bureau report. Payments are non-refundable, no partial credits. Long history as the default credit-monitoring affiliate inside Credit Repair Cloud, Client Dispute Manager, and DisputeFox — a meaningful share of credit repair pros know MFSN's name before they ever hear SmartCredit's." },
      { type:"THE REAL REASON", sub:"why this comparison is closer than it looks", pill:"#94A3B8", tag:"Be Precise", tagBg:"#F1F5F9", tagColor:"#475569",
        title:"Be honest: at the top tier, MFSN and SmartCredit are priced almost identically",
        summary:"At the top tier the prices are nearly identical — don't try to win this on price alone.",
        body:"MFSN's flat $29.95/month already includes a monthly 3-bureau report — that's comparable to SmartCredit's Premium tier at $27.95–$29.95. <span class='hl'>If you try to win this on price alone, a sharp agency owner will catch you in it within one Google search.</span> The real difference isn't the sticker price — it's that MFSN has been built as a self-serve affiliate funnel for over a decade, while SmartCredit's Co-Brand PLUS+ program is built as an actual partnership: a hosted site, named support, and documented commission. Win on the relationship, not a price gap that barely exists at parity." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"A link versus a partnership — this is the actual gap",
        summary:"MFSN gives you a link. SmartCredit builds a hosted co-branded site with a named contact — that's the real difference.",
        body:"MFSN's affiliate model is a self-serve link: apply, get a code, drop it in your CRM, done. <span class='hl'>SmartCredit's Co-Brand PLUS+ program builds you a hosted website under your own logo, assigns a named partner contact, and runs auto-nurture sequences to protect retention</span> — none of which a bare affiliate link does. One is a transaction. The other is infrastructure for your agency." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"MFSN pays once. SmartCredit pays every month the client stays active.",
        summary:"MFSN: $50 once. SmartCredit: $5–$15 every month the client stays active — the gap compounds forever.",
        body:"MFSN's affiliate commission is a <span class='hl'>flat $50, paid one time, per sale</span> — nothing further regardless of how long that client stays subscribed. SmartCredit's Co-Brand PLUS+ pays $5 to $15 in commission <span class='hl'>every single month</span> a client remains active. Full math in the Commission Comparison view: a client who stays a year is worth over 3x more through SmartCredit than MFSN's one-time bounty — from the identical client." },
      { type:"FAIR TRADE-OFF", sub:"be honest about this", pill:"#F59E0B", tag:"Genuine Gap", tagBg:"#FEF3C7", tagColor:"#92400E",
        title:"MFSN's decade of brand trust in this exact industry is real — and their CRC integration is more mature",
        summary:"MFSN's industry trust is real, and both platforms use a similar manual-style CRC import — win this on partnership, not tech.",
        body:"MFSN has been the default monitoring affiliate inside Credit Repair Cloud-style platforms for over ten years; a lot of agency owners have never had a bad experience with it and have no reason to switch. <span class='hl'>SmartCredit and MFSN both currently rely on a copy/paste-style import into Credit Repair Cloud</span> rather than a fully automated API sync — neither has a clean technical edge there. Win this deal on the partnership and commission structure, not on a technical claim that won't survive a demo." },
      { type:"2026 INTEL", sub:"live data", pill:"#7C3AED", tag:"New", tagBg:"#EDE9FE", tagColor:"#6D28D9",
        title:"MFSN launched ITIN compatibility first — know this before a prospect brings it up",
        summary:"MFSN was first to offer full 3-bureau access for ITIN holders (April 2026) — know this before it comes up.",
        body:"MFSN announced it is the first credit monitoring platform to give consumers <span class='hl'>without a Social Security Number full online access to all three bureaus via ITIN compatibility</span> (April 2026) — relevant to roughly 5 million active ITIN holders. This is a genuine, current differentiator for agencies serving immigrant and underbanked communities. Acknowledge it if it comes up; don't get caught flat-footed." },
      { type:"TALK TRACK", sub:"scenario 1", pill:"#6366F1", tag:"Reframe", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"'I already have an MFSN affiliate link — why switch?'",
        summary:"A link is a transaction. SmartCredit's Co-Brand PLUS+ is a partnership — hosted site, named contact, real commission.",
        body:"\"MFSN's link works — I'm not going to tell you it doesn't. But it's just a link: you sign up, get a code, and that's the entire relationship. SmartCredit's Co-Brand PLUS+ program builds you a hosted website under your own logo, assigns a named contact on our team, and pays a documented $5 to $15 a month per active client depending on tier. <span class='hl'>You're not just swapping one monitoring product for another — you're trading a transaction for an actual partnership.</span>\"" },
      { type:"TALK TRACK", sub:"scenario 2", pill:"#6366F1", tag:"Honest", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Prospect points out MFSN and SmartCredit are priced the same",
        summary:"Agree on price parity, then pivot: the partnership and commission structure aren't equal even when the price is.",
        body:"\"You're right, and I'd rather tell you that straight than pretend otherwise — at the top tier, the prices are close. The difference isn't the number on the invoice. It's that MFSN is a self-serve affiliate link, and SmartCredit is a built partnership: your own co-branded site, a named contact, and <span class='hl'>a documented commission structure that pays more as your enrollment volume grows.</span> If the prices are a wash, the partnership shouldn't be.\"" },
      { type:"TALK TRACK", sub:"scenario 3", pill:"#6366F1", tag:"Retention", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Agency worried about client churn on a monitoring add-on",
        summary:"SmartCredit's auto-nurture sequences actively work to prevent cancels — steadier commission, better client experience.",
        body:"\"Churn on any third-party add-on happens when nobody's actively working to keep that client engaged after signup. SmartCredit's auto-nurture sequences exist specifically to <span class='hl'>prevent cancels</span> — which means steadier monthly commission for you and a better experience for your client. A bare affiliate link doesn't do any of that work for you.\"" },
      { type:"LANDMINE", sub:"question 1", pill:"#F59E0B", tag:"Plant", tagBg:"#FEF9C3", tagColor:"#92400E",
        title:"Who's actually working to keep your MFSN-referred clients from canceling?",
        summary:"Once an MFSN client signs up, nothing actively keeps them engaged. Ask who's doing that work.",
        body:"\"Once a client signs up through an affiliate link, what happens next is mostly automatic. <span class='hl'>Who's nurturing that relationship</span> to make sure they don't cancel in month two when life gets busy?\"" }
    ]
  },
  idiq: {
    name:"IDIQ (IdentityIQ / MyScoreIQ)", threat:"high", pill:"HIGH THREAT",
    sub:"Temecula, CA · IdentityIQ® + MyScoreIQ® · 4 tiers, $6.99–$39.95/mo · 2-tier Partner + Referral Partner program",
    link:"https://www.identityiq.com", linkLabel:"identityiq.com",
    blocks:[
      { type:"OVERVIEW", sub:"profile", pill:"#14B8A6", tag:"Larger Suite", tagBg:"#CCFBF1", tagColor:"#0D9488",
        title:"IDIQ — Core Profile (Two Brands, One Parent)",
        summary:"Two brands, four pricing tiers, a two-layer Partner/Referral Partner structure.",
        body:"Founded 2009, based in Temecula, CA. Operates two consumer brands: <span class='hl'>IdentityIQ®</span> (identity theft protection + credit monitoring) and <span class='hl'>MyScoreIQ®</span> (FICO® scores + credit + identity). Four IdentityIQ tiers — Secure Basic ($6.99–$8.49), Secure Plus ($11.49–$19.99), Secure Pro (~$19.99), Secure Max ($27–$29.99) — plus an optional Bitdefender antivirus/VPN bundle. B2B model runs on a two-tier 'Partner' (residual per enrollment) and 'Referral Partner' (percentage of a referred partner's monthly revenue) structure." },
      { type:"THE REAL REASON", sub:"why this gap exists", pill:"#94A3B8", tag:"Portfolio Strategy", tagBg:"#F1F5F9", tagColor:"#475569",
        title:"Why a 4-tier, 2-brand structure exists — and why it creates real friction",
        summary:"More tiers means more upsell paths — and more room for a client to land on the wrong plan.",
        body:"Running two consumer brands and four pricing tiers is a deliberate strategy to capture customers at every price point and maximize the number of upsell paths. <span class='hl'>The cost of that strategy is complexity: more tiers to explain correctly, more room for a client to land on the wrong one, and a two-layer partner structure where your income can depend on someone else's recruiting activity.</span> SmartCredit chose the opposite trade-off — one consumer product line, fewer tiers, and a partner relationship that pays you directly for what you personally enroll. Less surface area to capture revenue from, but far less room for things to go wrong in front of a client." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"Simpler onboarding — IDIQ's own reviewers warn against one of its 4 tiers",
        summary:"U.S. News explicitly says not to use one of IDIQ's four tiers. SmartCredit has one clear plan, every time.",
        body:"U.S. News' 2026 review of Secure Plus literally states: <span class='hl'>\"Let us be clear: we do not recommend this plan.\"</span> That's a third-party admission that IDIQ's tier structure creates real risk of mis-selling a client into the wrong plan. SmartCredit's co-brand setup is a single clear path — same plan structure, same onboarding flow, every time." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"A published rate beats an undisclosed one, every time",
        summary:"IDIQ's Partner tier pays real residual income — but the rate is negotiated, not published like SmartCredit's.",
        body:"To be fair, IDIQ's Partner tier genuinely pays recurring monthly residual income, not just a one-time bounty — credit where it's due. <span class='hl'>But the exact rate isn't publicly published; it's negotiated per partner.</span> SmartCredit's Co-Brand PLUS+ commission table is openly documented — $5 to $15 per active client by tier, no negotiation required, no guessing what you'll actually be paid before you sign anything. Full breakdown of both programs is in the Commission Comparison view." },
      { type:"FAIR TRADE-OFF", sub:"be honest about this", pill:"#F59E0B", tag:"Genuine Gap", tagBg:"#FEF3C7", tagColor:"#92400E",
        title:"IDIQ's breadth is real, and MyScoreIQ's FICO offering is a legitimate edge",
        summary:"Two brands, a real FICO option, and a security bundle — genuinely the most built-out portfolio in this comparison.",
        body:"Two established brands, an actual FICO® score product in MyScoreIQ, a security bundle through Bitdefender, and a long-running partner dashboard with enrollment tracking — this is the most fully-built product portfolio in the entire comparison. <span class='hl'>If a prospect specifically wants to offer clients a real FICO option under one umbrella with their credit tools, IDIQ covers that in a way SmartCredit currently doesn't.</span> The honest pitch isn't that IDIQ is thin — it's that bigger created complexity SmartCredit chose not to take on." },
      { type:"2026 INTEL", sub:"live data", pill:"#7C3AED", tag:"Critical", tagBg:"#EDE9FE", tagColor:"#6D28D9",
        title:"U.S. News declined to rank IdentityIQ in 2026 — cited price and thin features",
        summary:"Left off U.S. News' 2026 list for high price and thin features; also reported to share customer data with third parties.",
        body:"U.S. News' 2026 review: IdentityIQ <span class='hl'>\"didn't make our ranking of the best identity theft protection plans in 2026 due to a combination of high prices and minimal feature sets.\"</span> Security.org separately notes IdentityIQ sells customer information to third parties. Both are useful, fact-based context if a prospect raises IDIQ's size as a reason to switch." },
      { type:"TALK TRACK", sub:"scenario 1", pill:"#6366F1", tag:"Pivot", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"'IDIQ has a bigger suite — identity, credit, scores, everything'",
        summary:"Broad isn't simple — one tier is flagged as not worth using, and earnings can depend on someone else's recruiting.",
        body:"\"IDIQ's suite is genuinely broad — I won't argue that. But broad isn't the same as simple, and their own reviewers have flagged one of the four IdentityIQ tiers as not worth recommending. The two-layer Partner and Referral Partner structure also means your income can depend on someone else's recruiting, not just your own enrollments. <span class='hl'>SmartCredit keeps it to one clear plan and a direct partnership</span> — what you bring in is what you're paid on, full stop.\"" },
      { type:"TALK TRACK", sub:"scenario 2", pill:"#6366F1", tag:"Trust", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Prospect is drawn to IDIQ's $6.99 entry tier",
        summary:"That's an anchor price for bare-bones, single-bureau coverage — real 3-bureau monitoring costs more than SmartCredit.",
        body:"\"That $6.99 tier is single-bureau, bare-bones coverage — it's an anchor price more than something most agencies actually hand to clients. Once you move up to a tier with real 3-bureau monitoring, the price climbs past where SmartCredit starts, and the tier confusion has already been flagged publicly by independent reviewers. <span class='hl'>SmartCredit's pricing is straightforward from the first conversation</span> — no asterisk on the headline number.\"" },
      { type:"TALK TRACK", sub:"scenario 3", pill:"#6366F1", tag:"Privacy", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Agency cares about client data practices",
        summary:"Security.org reports IdentityIQ shares customer data with third parties — a real trust consideration for anxious clients.",
        body:"\"Worth knowing: Security.org has reported that IdentityIQ shares customer information with third parties. If your clients are already anxious about their financial data being exposed — which, given why they're in credit repair, many are — <span class='hl'>that's a real trust consideration,</span> not a minor footnote.\"" },
      { type:"LANDMINE", sub:"question 1", pill:"#F59E0B", tag:"Plant", tagBg:"#FEF9C3", tagColor:"#92400E",
        title:"Which of IDIQ's 4 tiers are your clients actually on?",
        summary:"Reviewers flagged one tier as not worth using — are all your clients confidently on the right one?",
        body:"\"There are four tiers, and reviewers have publicly said not to use one of them. <span class='hl'>Are you confident every one of your clients is on the right plan</span> — or could some be paying for the one reviewers flagged?\"" }
    ]
  },
  array: {
    name:"Array", threat:"low", pill:"DIFFERENT CATEGORY",
    sub:"Enterprise embedded-finance API · Sells to banks/credit unions/fintechs, not credit repair agencies",
    link:"https://array.com", linkLabel:"array.com",
    blocks:[
      { type:"OVERVIEW", sub:"profile", pill:"#7C3AED", tag:"Different Buyer", tagBg:"#EDE9FE", tagColor:"#6D28D9",
        title:"Array — Core Profile (Read This Before You Pitch)",
        summary:"Enterprise embedded-finance platform for banks and credit unions — not a consumer product, no individual affiliate program.",
        body:"Founded 2020 (Martin Toha, Phillip Zedalis), backed by Battery Ventures, General Catalyst, and Nyca Partners. <span class='hl'>Array is not a consumer product and does not run a simple affiliate program.</span> It's a B2B embedded-finance platform: banks, credit unions, and fintechs license Array's white-label tools — My Credit Manager, Offers Engine, ID Protect, Debt Manager, BuildCredit Loans — and embed them directly into their own digital banking app. Live inside Jack Henry's Banno platform (800+ community banks/CUs, 10M+ users), Alkami, and DCI's core banking system." },
      { type:"THE REAL REASON", sub:"why this category difference exists", pill:"#94A3B8", tag:"Capital Strategy", tagBg:"#F1F5F9", tagColor:"#475569",
        title:"Why a VC-backed platform chases banks instead of credit repair agencies",
        summary:"VC-backed growth needs enterprise-scale contracts — a single agency's client book isn't a meaningful unit of growth for Array.",
        body:"Array raised institutional venture capital from firms like Battery Ventures and General Catalyst, which means its growth has to look like enterprise contracts with banks and credit unions serving millions of account holders at once — that's the scale a VC-backed return profile requires. <span class='hl'>A single credit repair agency with a few hundred clients isn't a meaningful unit of growth at that scale,</span> which is exactly why Array has never built an affiliate or agency channel. SmartCredit's Co-Brand PLUS+ model was built for the opposite shape of customer: hundreds of individual agencies, each bringing their own book of clients." },
      { type:"QUALIFY FIRST", sub:"before you pitch", pill:"#1B65E5", tag:"Critical", tagBg:"#DBEAFE", tagColor:"#1D4ED8",
        title:"Array is a different sales motion — qualify the buyer before comparing products",
        summary:"A referral link means SmartCredit. A custom in-app integration means Array — qualify which one before pitching either.",
        body:"If your prospect wants a <span class='hl'>referral link to hand clients</span>, they are not an Array-style buyer — they're in SmartCredit/MFSN/IDIQ territory and Array isn't a realistic option for them. If your prospect is a bank, credit union, or fintech that wants <span class='hl'>their own branded, in-app credit experience built into their own platform</span>, that's a custom integration conversation — different sales cycle, different stakeholders (often includes engineering/IT), and likely outside a standard BDR deal size. Ask which one you're actually in before building a comparison." },
      { type:"YOUR WIN", sub:"advantage", pill:"#22C55E", tag:"Edge", tagBg:"#DCFCE7", tagColor:"#15803D",
        title:"Speed to revenue — SmartCredit's affiliate/co-brand path launches in days, not months",
        summary:"Array is a multi-month enterprise build. SmartCredit's affiliate link and co-branded site are live same-day.",
        body:"Array engagements are enterprise integrations: API implementation, IT/engineering involvement, and a multi-month build-and-launch timeline before a financial institution's customers see anything. <span class='hl'>SmartCredit's affiliate link is live same-day; a full co-branded site is built for you</span> — no developer required. For any agency or business that isn't already running its own digital banking platform, SmartCredit is operational immediately." },
      { type:"FAIR TRADE-OFF", sub:"be honest about this", pill:"#F59E0B", tag:"Genuine Gap", tagBg:"#FEF3C7", tagColor:"#92400E",
        title:"For the right buyer, Array's depth of integration is something SmartCredit doesn't offer",
        summary:"For a bank wanting native in-app tools, Array solves a real problem SmartCredit's model wasn't built for — recognize it and route it.",
        body:"A bank that wants credit tools to feel like a native part of their own app — not a redirect to a third-party site — gets something real from Array's API approach that SmartCredit's affiliate/co-brand model was never built to deliver. <span class='hl'>This isn't a worse product losing on merit; it's a different product solving a different integration problem.</span> The honest move is recognizing that fast and routing it, not trying to force a co-brand pitch onto a buyer who actually needs an engineering conversation." },
      { type:"INTERNAL NOTE", sub:"confidential — read fully", pill:"#6B7280", tag:"Do Not Use Offensively", tagBg:"#F3F4F6", tagColor:"#374151",
        title:"Litigation history exists between ConsumerDirect and Array — internal awareness only",
        summary:"Internal awareness only — documented litigation history exists. Never raise this; escalate if it comes up.",
        body:"<strong>This is background information for your own awareness, not a talking point.</strong> ConsumerDirect filed suit against Array (and Pentius LLC) in December 2021 over trademark infringement, cybersquatting, and unfair competition claims. The case went to trial in October 2023, and on November 8, 2023 a federal jury in Santa Ana, CA ruled unanimously against ConsumerDirect on every claim — and awarded Array $1.3M in actual damages plus $3.9M in punitive damages. The court's August 2024 final judgment additionally found that ConsumerDirect had committed fraud on the court (fabricated evidence, backdated documents) and ordered ConsumerDirect to pay further sanctions. <span class='hl'>Do not raise this with a prospect, partner, or Array representative under any circumstance.</span> If it comes up from the other side, do not improvise a response — say you're not the right person to speak to it and loop in your manager." },
      { type:"2026 INTEL", sub:"live data", pill:"#7C3AED", tag:"Market Note", tagBg:"#EDE9FE", tagColor:"#6D28D9",
        title:"Array continues expanding bank/credit union distribution, not agency-channel distribution",
        summary:"All of Array's 2026 partnerships are financial-institution deals — no sign of an agency channel forming.",
        body:"Array's recent partnership announcements (DCI, ongoing Jack Henry/Banno rollout) are all on the financial-institution side — <span class='hl'>there is no indication Array is building an affiliate or credit-repair-agency channel</span> to compete with SmartCredit, MFSN, or IDIQ in that space. This reinforces that Array is a category difference, not a head-to-head agency competitor, for the vast majority of BDR conversations." },
      { type:"TALK TRACK", sub:"scenario 1", pill:"#6366F1", tag:"Qualify", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Prospect mentions they're 'looking at Array too'",
        summary:"Ask if they need a referral link or a custom in-app build — that question routes the entire conversation.",
        body:"\"Just so I point you in the right direction — are you looking for a credit tool you can hand clients via a referral link, or are you looking to build credit features directly into your own app or platform? Those are pretty different paths. SmartCredit is built for the first — live same-day, no developer needed. Array is built for the second — financial institutions embedding tools into their own software, which is a longer technical build.\"" },
      { type:"TALK TRACK", sub:"scenario 2", pill:"#6366F1", tag:"Route", tagBg:"#EEF2FF", tagColor:"#4F46E5",
        title:"Prospect IS a bank or credit union wanting in-app credit tools",
        summary:"Route this to the right team — it's an engineering conversation, not a standard co-brand pitch.",
        body:"\"If you're looking to build credit monitoring natively into your own digital banking app, that's a different conversation than what we typically set up — it usually involves your engineering team and a longer implementation timeline. Let me make sure I connect you with the right team here so you get an accurate scope and timeline rather than me guessing at a fit that isn't ours to promise.\"" },
      { type:"LANDMINE", sub:"question 1", pill:"#F59E0B", tag:"Qualify", tagBg:"#FEF9C3", tagColor:"#92400E",
        title:"Do you need a referral link, or a custom integration into your own platform?",
        summary:"A referral link means SmartCredit is live today. A custom integration is an entirely different category of vendor.",
        body:"\"This is the one question that tells you everything. <span class='hl'>A referral link means SmartCredit is live for you today.</span> A custom integration means you're evaluating a different category of vendor entirely, and the timeline and conversation should be set accordingly.\"" }
    ]
  }
};
