'use client'

// Meeting rooms — list + create. A room is a mode (1:1 / team / boardroom / war
// room / office hours) plus its agent participants; boardrooms get a chair
// (Chief of Staff) who synthesizes. Turns are generated by /api/team/room.

import { useCallback, useEffect, useState } from 'react'
import { createUntypedClient } from '@/lib/supabase/untyped'

export interface Room {
  id: string; mode: string; topic: string | null; chair_agent_id: string | null
  status: string; created_at: string; updated_at: string
}

export const ROOM_MODES = [
  { k: 'one_on_one', label: '1:1 Chat', help: 'Focused work with one teammate', chair: false },
  { k: 'team', label: 'Team Chat', help: 'A few teammates think together', chair: false },
  { k: 'boardroom', label: 'Boardroom', help: 'Chief of Staff chairs; ends with decisions', chair: true },
  { k: 'war_room', label: 'War Room', help: 'Urgent launch or performance push', chair: true },
  { k: 'office_hours', label: 'Office Hours', help: 'Advisory session with a role', chair: false },
]

export function useRooms() {
  const supabase = createUntypedClient()
  const [loading, setLoading] = useState(true)
  const [rooms, setRooms] = useState<Room[]>([])
  const [nonce, setNonce] = useState(0)
  const reload = useCallback(() => setNonce(n => n + 1), [])

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      setLoading(true)
      const { data } = await supabase.from('meeting_rooms').select('*').order('updated_at', { ascending: false })
      if (cancelled) return
      setRooms(data ?? []); setLoading(false)
    })()
    return () => { cancelled = true }
  }, [nonce, supabase])

  const createRoom = async ({ mode, topic, agentIds, chairId }: { mode: string; topic: string; agentIds: string[]; chairId?: string | null }) => {
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { error: 'Not signed in' }
    const { data: me } = await supabase.from('users').select('team_id').eq('id', user.id).maybeSingle()
    const { data: room, error } = await supabase.from('meeting_rooms')
      .insert({ user_id: user.id, team_id: me?.team_id ?? null, mode, topic: topic || null, chair_agent_id: chairId ?? null })
      .select('*').maybeSingle()
    if (error || !room) return { error: error?.message || 'Could not create room' }
    const rows = agentIds.map(id => ({ room_id: room.id, user_id: user.id, agent_id: id, role: id === chairId ? 'chair' : 'member' }))
    if (rows.length) await supabase.from('meeting_participants').insert(rows)
    reload()
    return { id: room.id }
  }

  return { loading, rooms, reload, createRoom }
}
