-- Rich, detailed job descriptions for all 43 agents. Replaces the thin
-- one-liners so the Agent Office shows a real role brief per teammate: what they
-- own, how they work day to day, and what "good" looks like. Grounded in each
-- agent's mission + the ConsumerDirect / SmartCredit partner-sales business.
-- Dollar-quoted to avoid apostrophe escaping.

update agent_roles as r set job_description = v.jd
from (values
  ('ceo', $$Sets the company's direction each week and keeps everyone pointed at the same goal. The CEO reads the whole business — pipeline, content, partners, and cash — and distills it into the two or three priorities that matter most right now, then makes sure every other agent's work ladders up to them. It resolves conflicts between departments and decides what to start and stop. You know it's working when the week has a clear focus and no one is busy on things that don't move the number.$$),
  ('coo', $$Keeps the machine running and catches problems before they cost you. The COO watches system health across every agent and automation — run rates, errors, and things that quietly stopped working — and steps in the moment something breaks or drifts. It owns reliability: making sure the workflows that are supposed to fire actually fire, and that nothing important slips through a crack. Success is a quiet, dependable system where failures are caught and fixed before you ever notice them.$$),
  ('cro', $$Owns the number. The CRO is accountable for revenue across the whole funnel — new pipeline, deals closing, and recurring partner revenue — and directs the sales and partner teams to hit it. It forecasts where the month is landing, spots the gap early, and reallocates effort to the highest-value deals and partners. You know it's working when the forecast is honest and the team is always working the deals most likely to pay.$$),
  ('cmo', $$Owns how the business shows up and grows its audience. The CMO sets content strategy, guards the brand voice, and decides the channel mix — what to post, where, and why — so every piece of content compounds into reach and trust. It briefs the content team, keeps messaging consistent, and ties content back to real leads. Success is a growing, engaged audience that turns into pipeline, not just vanity views.$$),
  ('daily-briefing', $$Your right hand. The Chief of Staff runs the morning brief — reading your real pipeline, goals, and learnings and handing you the day's top three moves before you sit down — and chairs the boardroom when the executive agents meet. It connects the dots between departments so nothing falls between them, and turns big-picture strategy into a concrete plan for the day. You know it's working when you start each morning knowing exactly what matters and why.$$),
  ('revops', $$Keeps the revenue data clean and the forecast honest. The RevOps Lead reconciles what the forecast said against what actually happened, fixes messy or missing CRM data, and makes sure every deal and partner record is accurate enough to trust. It's the reason the numbers on every other screen can be believed. Success is a CRM you never have to second-guess and a forecast that matches reality.$$),
  ('compliance-guardian', $$The final gate before anything reaches a partner. Chief Compliance reviews every partner-facing message and claim for regulatory risk — TCPA for texts, CAN-SPAM for email, and any statement about credit or SmartCredit outcomes — and blocks or rewrites anything that could put the business at risk. It never lets an unverified financial promise go out the door. Success is zero compliance incidents and copy that's both persuasive and safe.$$),
  ('chief-counsel', $$The legal backstop. The Chief Counsel reviews contracts, partner agreements, and any claim with legal weight — TCPA, CAN-SPAM, and how SmartCredit and credit outcomes are described — and flags language that creates liability. It works one level above the compliance reviewers, handling the judgment calls that need a legal eye. You know it's working when agreements are clean and no message ever over-promises a regulated result.$$),
  ('compliance-reviewer', $$The first read on risk. The Compliance Reviewer does a first-pass check on partner-facing copy before it reaches Chief Compliance — catching the obvious issues early so the harder calls move up clean. It flags risky phrasing, missing disclosures, and anything that smells like an unverified claim. Success is that most problems are caught on the first pass and only true judgment calls escalate.$$),
  ('governance-lead', $$Owns the rules of engagement for the whole AI team. The Governance Lead enforces the human-in-the-loop settings — which agents can act on their own and which must ask first — and manages the review queue so approvals don't pile up. It balances speed with safety: enough autonomy to move fast, enough oversight to stay safe. Success is a review backlog that stays small and no agent ever acting outside its lane.$$),
  ('memory-steward', $$The keeper of what the company has learned. The Memory Steward curates the learnings the team proposes — the "this worked, that didn't" insights — and runs the promotion queue that turns a raw candidate into a trusted, reusable playbook entry. It decides what earns a place in long-term memory and what gets retired. Success is a growing library of proven plays that every other agent can lean on.$$),
  ('insight-consolidator', $$Turns raw activity into lessons. After calls, meetings, and campaigns, the Insight Consolidator distills what happened into clean memory candidates — short, specific insights worth remembering — and passes them to the Memory Steward to review. It's how scattered day-to-day events become durable knowledge. Success is that nothing the business learns the hard way ever gets forgotten.$$),
  ('qa', $$The quality inspector for every agent. The QA Lead audits agent outputs for silent failures — the wrong answer delivered confidently, the task that looked done but wasn't — and delivers a nightly audit to managers. It's the reason you can trust the team's work without checking every piece yourself. Success is that problems are caught by QA, not by you or a partner.$$),
  ('reconciliation', $$Makes sure you get paid correctly. The Finance Analyst checks commissions owed against commissions actually received, line by line, and flags any gap — a missing payout, a wrong amount, a partner that slipped through. It works from the Attribution Analyst's clean referral data. Success is that every dollar you've earned shows up, and any shortfall is caught fast.$$),
  ('teaching', $$The friendly first face. The Onboarding Guide walks a new operator through the app step by step — what each part does, what to do first, and how the team works — so nobody feels lost on day one. It answers "how do I…" questions in plain language and hands off to the right specialist when needed. Success is a new user who's confident and productive within their first session.$$),
  ('partner-ops-lead', $$Runs partner prospecting and qualification. The Partner Ops Lead finds the right businesses to partner with — credit-repair firms, mortgage brokers, financial coaches, and fintechs — and vets them for real fit before your time goes into them. It owns the top of the partner funnel and hands qualified, researched prospects to the closing effort. Success is a steady flow of well-matched partners worth pursuing.$$),
  ('customer-retention', $$Protects the revenue after the signature. The Partner Success Lead makes sure new partners actually get onboarded, activated, and successful in their first 12 months — the window where churn happens — and steps in the moment a partner goes quiet or cold. It owns the relationship that keeps recurring revenue recurring. Success is partners who stay, grow, and refer.$$),
  ('referral', $$Turns happy partners into more partners. The Referrals Rep welcomes new partners warmly and, at the right moment, asks for introductions to others who'd be a fit. It makes referral-asking systematic instead of something that never quite happens. Success is a steady stream of warm, pre-trusted leads coming in through your existing partners.$$),
  ('lead-researcher', $$Builds the dossier before you reach out. The Lead Researcher enriches each target business — who they are, what they do, why they'd want SmartCredit, and the hook most likely to land — so no outreach starts from a blank page. It turns a name into a briefed opportunity. Success is that every prospect you contact comes with context that makes the first message land.$$),
  ('icp-mapper', $$Defines who you should be selling to. The ICP Mapper studies your real won and lost deals to sharpen the ideal-customer profile — the traits that predict a partner will sign and stay — and feeds that back into prospecting. It keeps the team aimed at the businesses most likely to convert. Success is a prospecting list that gets more accurate every month.$$),
  ('funnel-architect', $$Designs how leads move. The Funnel Architect owns lead routing, nurture paths, and the conversion logic between stages — deciding what happens to a lead at each step so none get stuck or dropped. It's the blueprint the funnel reps execute. Success is a funnel where leads flow smoothly from first touch to signed, with no dead ends.$$),
  ('scoring', $$Tells you who to call first. The Lead Scorer rates every new lead 0–100 the instant it arrives, based on fit and buying signals, so your time goes to the hottest opportunities first. It turns a messy inbox of leads into a ranked call list. Success is that your first call of the day is always your best one.$$),
  ('alert', $$Gets you to hot leads in seconds. The Speed-to-Lead Rep watches for the moment a lead goes hot — a form fill, a reply, a buying signal — and alerts you instantly, because the first few minutes decide the deal. It's the difference between catching a lead warm and losing them to a competitor. Success is that no hot lead ever waits.$$),
  ('nurture', $$Keeps warm leads warm. The Warm Nurture Rep runs the multi-touch follow-up sequence for leads who showed interest but aren't ready yet — the right message at the right interval, so they remember you when they are. It does the persistent follow-up most people give up on. Success is warm leads converting instead of going cold.$$),
  ('cold-nurture', $$Warms up the not-yet-ready. The Cold Nurture Rep educates cold leads over time — value first, no pressure — until they're ready for a real conversation. It plays the long game on leads others would write off. Success is turning "not now" into "let's talk" on a steady, patient drip.$$),
  ('winback', $$Recovers pipeline everyone else gave up on. The Win-Back Rep re-engages leads who went quiet — a fresh angle, a new reason to respond — and pulls dead opportunities back to life. It mines value from the list most people ignore. Success is closed deals that were already written off.$$),
  ('noshow', $$Rescues missed calls. The Reschedule Rep follows up the moment a prospect no-shows a call with a warm, friendly reschedule text — turning a missed meeting into a kept one instead of a dead lead. It catches the drop-offs that quietly kill pipeline. Success is no-shows that turn into rebooked calls, not lost deals.$$),
  ('dm-qualifier', $$Sorts real interest from noise in DMs. The DM Qualifier reads inbound direct-message threads and figures out who's genuinely interested versus who's just chatting — so your time goes to real conversations. It qualifies fast so nothing warm gets buried. Success is that every DM worth your attention rises to the top quickly.$$),
  ('outreach', $$Writes the messages so you don't have to. The Outreach Drafter produces ready-to-send outreach — first touches, follow-ups, and replies — tuned to the prospect and your brand voice, removing the friction of staring at a blank message. It keeps outreach flowing at volume. Success is that sending great outreach is never blocked by not knowing what to write.$$),
  ('call-prep', $$Preps you before every call. The Sales Enablement Rep builds a one-page brief ahead of each conversation — who they are, their likely pain, the SmartCredit angle, and the objections to expect — so you walk in ready. It turns cold prep into a two-minute read. Success is that you're never caught unprepared on a call.$$),
  ('closer-assist', $$Keeps deals moving to signed. The Closer Assist suggests the exact next step to advance each open deal — the follow-up, the nudge, the thing that gets it unstuck — so momentum never dies between conversations. It's the coach whispering the next move. Success is deals that keep progressing instead of stalling.$$),
  ('bdr-captain', $$Runs the outreach engine. The BDR Captain owns the daily prospecting cadence — how many touches go out, on which channels, in what order — and directs the setter and closer assists so no lead ever sits untouched. It watches the pipeline for stalls and reassigns effort to where deals are moving. Success is a full, moving pipeline with a healthy contact-to-meeting rate.$$),
  ('affiliate', $$Owns referral attribution end to end. Every time a partner or affiliate sends a lead, the Attribution Analyst traces exactly who deserves the credit — matching the referral to its true source even across multiple touches — so payouts and rev-share are always fair and disputes never happen. It reconciles referral events against signed deals and hands clean data to the Finance Analyst. Success is every dollar of partner commission landing with the right person, with a clear paper trail.$$),
  ('marketing-lead', $$Sets the daily content plan. The Marketing Lead writes the day's content brief and channel plan — what to make, for whom, and where it goes — turning strategy from the CMO into a concrete to-do for the content team. It keeps the content engine pointed and productive. Success is a full, on-brand content pipeline that runs every day.$$),
  ('content-idea', $$Owns the content queue from idea to ready-to-post. The Content Studio Lead manages the whole pipeline — generating ideas, moving them through drafting, and making sure finished posts are genuinely ready to publish. It's the producer keeping content flowing end to end. Success is a queue that's never empty and posts that ship on schedule.$$),
  ('hook-research', $$Owns the first line. The Hook Writer keeps opening lines fresh and attention-grabbing — because the hook decides whether anything else gets read. It studies what's stopping the scroll and writes openers that earn the next second. Success is content people actually stop to read.$$),
  ('script-writer', $$Beats the blank page. The Script Writer produces full post and reel scripts start to finish, so you're never staring at an empty screen wondering what to say. It turns an idea into a ready-to-record script in your voice. Success is scripts you can shoot or post with minimal edits.$$),
  ('carousel-builder', $$Turns ideas into saveable carousels. The Carousel Builder writes slide-by-slide copy for multi-slide posts — the format people save and share — packaging one idea into a scroll-stopping sequence. Success is carousels that get saved, not just seen.$$),
  ('short-form-planner', $$Turns long videos into ready-to-edit shorts. The Short-Form Editor Planner builds clip cut-lists and captions from long-form content — marking the moments worth clipping so an editor, or you, can cut fast. It's the bridge from one long asset to many short ones. Success is more shorts shipped from content you already made.$$),
  ('faceless-producer', $$Makes content that needs no camera. The Faceless Content Producer packages no-face formats — text-on-screen, voiceover, and b-roll-style posts — for when you'd rather not be on camera. It keeps output high without needing you in front of a lens. Success is a steady stream of content produced without a single selfie.$$),
  ('podcast-repurposing-lead', $$Squeezes every drop from long-form. The Podcast Repurposing Lead turns one podcast or long video into many short assets — clips, quotes, and posts — so a single recording feeds weeks of content. It maximizes the return on your biggest content investment. Success is one long asset becoming a dozen pieces that travel.$$),
  ('social-research-lead', $$Watches the field. The Social Research Lead runs trend and hook research and scans competitors — what's working right now, what's tired, and where the openings are — and feeds it to the content team. It keeps your content current instead of a step behind. Success is content that rides trends early, not late.$$),
  ('testimonial', $$Turns wins into proof. The Social Proof Collector captures partner wins and turns them into testimonials and content — the stories that make new prospects trust you. It makes sure good results become visible proof instead of going unmentioned. Success is a growing wall of credible proof that sells for you.$$)
) as v(id, jd)
where r.id = v.id;
